---
# Update:
#   Jul 7th 2018

# Validate version: choose one below
#   1.9.0 - 1.9.9
#   1.10.0 - 1.10.5
#   1.11.0
kube_version: 1.9.9

# CNI plugin,
# Supported: calico, flannel, weave, canal or router.
network: calico
pod_network_cidr: 10.244.0.0/16

# CNI opts,
# flannel(--iface=enp0s8), calico(interface=enp0s8), canal(enp0s8).
cni_iface: ""

# Kubernetes cluster network.
cluster_subnet: 10.96.0
kubernetes_service_ip: "{{ cluster_subnet }}.1"
service_ip_range: "{{ cluster_subnet }}.0/12"
service_node_port_range: 30000-32767
api_secure_port: 5443

# Highly Available configuration.
haproxy: true
keepalived: true # set `lb_vip_address` as keepalived vip, if this enable.
keepalived_vip_interface: "{{ ansible_default_ipv4.interface }}"

lb_vip_address: 10.0.100.100
lb_secure_port: 6443
lb_api_url: "https://{{ lb_vip_address }}:{{ lb_secure_port }}"

# Etcd configuration variables.
etcd_initial_token: etcd-k8s-cluster
etcd_domain_name: etcd.tkokok.top
etcd_iface: ""

# Kubernetes authentication and security
bootstrap_token: b96cee11d16de85256d63efd2e18e7d8
extra_auth:
  basic:
    accounts:
    - 'admin,p@ssw0rd,admin'
  # token:
  #   values:
  #   - "0fdd1a8875ec,admin,admin"

encryption_token: iTNwwjHuxNI9+8niwh8GJKT5NQiHFqcOTrrhzYfhAvk=

# Core addons (Strongly recommend)
kube_dns: true
dns_name: cluster.local # cluster dns name
dns_ip: "{{ cluster_subnet }}.10"

kube_proxy: true
kube_proxy_mode: ipvs # support: iptables, userspace or ipvs(alpha).
kube_proxy_ipvs_scheduler: rr # depend on ipvs mode.

# Extra addons
kube_dashboard: true
kube_logging: true
kube_monitoring: true

ingress: true
ingress_type: nginx # support: nginx or traefik.

###
# resistry:    Docker Harbor          -- docker container
# repository:  Apache or nginx server -- static files


# NEW REGISTRY MANAGEMENT SYSTEM
local_registry:
  # if
  insecure: false
  insecure_registry: "192.168.1.185"
  # elif
  secure: true
  proxy: true
  self_signed_certificate: false
  secure_registry: "hub.tkokok.top"
  secure_proxy: "192.168.1.180"
  # else
  official_registry: "docker.io"

registry_namespace: "kubernetes"

# Inject the certificate(pem-key) to each host
import_certificate: "curl http://172.18.210.253/crt/lingyi-docker-registry.pem >> /etc/pki/tls/certs/ca-bundle.crt"
final_registry_url: "{% if local_registry.insecure %}{{local_registry.insecure_registry}}{% elif local_registry.secure %}{{local_registry.secure_registry}}{% else %}{{local_registry.official_registry}}{% endif %}"

# localrepository
local_repository: http://192.168.1.181/repo/k8s
#https://gitee.com/liu-rui/repo/raw/master


# Origin OPTS by @KyleBai
# Vars below are not in use.

# A list of insecure registrys you might need to define
add_registry:
# - "gcr.io"

insecure_registrys:
# - "172.16.35.9:5000"

# Enable docker registry
registry: false
registry_ui: false
registry_url: "172.16.35.9:5000"

docker_opts:
# - "HTTP_PROXY=http://proxy.example.com:80/"
# - "HTTPS_PROXY=https://proxy.example.com:443/"

# Enable and disable ceph cluster
ceph_cluster: false

# Add http and https proxy
proxy_env:
  http_proxy: "" # http://:<usr>@<passwd>:<ip>:<port>
  https_proxy: "" # https://<usr>:<passwd>@<ip>:<port>

# Offline mode area
repos_offline: false
repos_port: 80
repos_offline_url: "http://172.16.20.143:{{ repos_port }}"