---

addon_images:
  # kubernetes dashboard
  dashboard: "{{ final_registry_url }}/kubernetes/kubernetes-dashboard-amd64:v1.8.0"
  # Kube-dns
  kubedns: "{{ final_registry_url }}/kubernetes/k8s-dns-kube-dns-amd64:1.14.7"
  dnsmasq: "{{ final_registry_url }}/kubernetes/k8s-dns-dnsmasq-nanny-amd64:1.14.7"
  sidecar: "{{ final_registry_url }}/kubernetes/k8s-dns-sidecar-amd64:1.14.7"
  # Kubernetes monitor
  heapster: "{{ final_registry_url }}/kubernetes/heapster-amd64:v1.5.0-beta.2"
  resizer: "{{ final_registry_url }}/kubernetes/addon-resizer:1.7"
  influxdb: "{{ final_registry_url }}/kubernetes/heapster-influxdb-amd64:v1.3.3"
  grafana: "{{ final_registry_url }}/kubernetes/heapster-grafana-amd64:v4.4.3"
  # Kubernetes logging
  elasticsearch: "{{ final_registry_url }}/kubernetes/elasticsearch:v5.6.2"
  fluentd: "{{ final_registry_url }}/kubernetes/fluentd-elasticsearch:v2.0.2"
  kibana: "{{ final_registry_url }}/kubernetes/kibana:5.6.2"
  # Ingress controller
  nginx_ingress: "{{ final_registry_url }}/kubernetes/nginx-ingress-controller:0.9.0"
  default_backend: "{{ final_registry_url }}/kubernetes/defaultbackend:1.4"
  traefik: "{{ final_registry_url }}/kubernetes/traefik:v1.5-alpine"
  # Kube-proxy
  kube_proxy: "{{ final_registry_url }}/kubernetes/kube-proxy-amd64:v{{ kube_version }}"
  
# Kube-addons resources
num_nodes: "{{ groups['kube-cluster'] | length }}"
base_metrics_memory: 140Mi
base_metrics_cpu: 80m
base_eventer_memory: 190Mi
metrics_memory_per_node: 4
metrics_cpu_per_node: 0.5
eventer_memory_per_node: 500
nanny_memory_per_node: 200
nanny_memory: "{% if num_nodes >= 0 -%}{{ 90 * 1024 + num_nodes|int * nanny_memory_per_node}}Ki{%- else -%}90Mi{% endif -%}"
dashboard:
  requests:
    memory: 128Mi
    cpu: 100m
dns:
  kubedns:
    limits:
      memory: 170Mi
    requests:
      cpu: 100m
      memory: 70Mi
  dnsmasq:
    requests:
      cpu: 150m
      memory: 20Mi
  sidecar:
    requests:
      memory: 20Mi
      cpu: 10m
monitor:
  resizer:
    limits:
      cpu: 80m
      memory: "{{ nanny_memory }}"
    requests:
      cpu: 50m
      memory: "{{ nanny_memory }}"
  influxdb:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi
  grafana:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
logging:
  kibana:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m
  fluentd:
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  elasticsearch:
    max_map_count: 262144
    limits:
      cpu: 500m
    requests:
      cpu: 100m
nginx_ingress:
  backend:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi
