# core components
major_version: 11
minor_version: 1
kube_version: 1.{{ major_version }}.{{ minor_version }}
kube_infra_image_version: 3.1

# dns components
kube_dns_version: 1.14.10
core_dns_version:
