---

addons:
  dashboard:
    files:
      - dashboard-rbac.yml
      - dashboard.yml
    name: kube-dashboard
  dns:
    files:
      - kube-dns.yml
    name: kube-dns
  efk_stack:
    files:
      - elasticsearch-rbac.yml
      - elasticsearch.yml
      - fluentd-configmap.yml
      - fluentd-daemonset.yml
      - fluentd-rbac.yml
      - kibana.yml
    name: efk-stack
  heapster:
    files:
      - heapster-rbac.yml
      - heapster.yml
      - influxdb-grafana.yml
    name: heapster
  prometheus:
    files:
    name: prometheus
  weave_scpoe:
    files:
      - weave-scope.yml
    name: weave-scope
  proxy:
    files:
      - kube-proxy-rbac.yml
      - kube-proxy.yml
    name: kube-proxy
  ingress:
    nginx:
      files:
      - nginx-ingress-rbac.yml
      - nginx-ingress-configmap.yml
      - default-backend.yml
      - nginx-ingress.yml
      name: nginx-ingress
    traefik:
      files:
      - traefik-ingress-rbac.yml
      - traefik-ingress.yml
      name: traefik-ingress
